//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Metro.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class test_linqsql1Entities : DbContext
    {
        public test_linqsql1Entities()
            : base("name=test_linqsql1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adjunto> Adjunto { get; set; }
        public DbSet<departamento1> departamento1 { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<into_sel> into_sel { get; set; }
        public DbSet<puesto1> puesto1 { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TicketArchivoAdjunto> TicketArchivoAdjunto { get; set; }
        public DbSet<TicketArchivoAdjunto2> TicketArchivoAdjunto2 { get; set; }
        public DbSet<TicketArchivoAdjunto3> TicketArchivoAdjunto3 { get; set; }
        public DbSet<user1> user1 { get; set; }
        public DbSet<view_test_1> view_test_1 { get; set; }
    }
}
