//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Metro.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class into_sel
    {
        public int id { get; set; }
        public string prueba { get; set; }
        public string codigo { get; set; }
    }
}
