//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Metro.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketArchivoAdjunto2
    {
        public decimal TicketArchivoAdjuntoId { get; set; }
        public int TicketId { get; set; }
        public string Descripcion { get; set; }
        public string Url { get; set; }
    }
}
